// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpRSBo3zCHDedbI2uaPLnrciiNAv1PphM',
    appId: '1:968202689571:web:afce767120bfc9e442a596',
    messagingSenderId: '968202689571',
    projectId: 'echoo-502fb',
    authDomain: 'echoo-502fb.firebaseapp.com',
    storageBucket: 'echoo-502fb.firebasestorage.app',
    measurementId: 'G-WNBL76KM67',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgMe8HBxveL7aDiHvzrYOGujl20ecplT4',
    appId: '1:968202689571:android:ff0f34c9496c986042a596',
    messagingSenderId: '968202689571',
    projectId: 'echoo-502fb',
    storageBucket: 'echoo-502fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZMuQPQ7AWNr9qXnn0hdXoN8-QBSzGME8',
    appId: '1:968202689571:ios:f427673c907fcec042a596',
    messagingSenderId: '968202689571',
    projectId: 'echoo-502fb',
    storageBucket: 'echoo-502fb.firebasestorage.app',
    iosBundleId: 'com.example.echoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZMuQPQ7AWNr9qXnn0hdXoN8-QBSzGME8',
    appId: '1:968202689571:ios:f427673c907fcec042a596',
    messagingSenderId: '968202689571',
    projectId: 'echoo-502fb',
    storageBucket: 'echoo-502fb.firebasestorage.app',
    iosBundleId: 'com.example.echoo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpRSBo3zCHDedbI2uaPLnrciiNAv1PphM',
    appId: '1:968202689571:web:aa8e9533fb08854e42a596',
    messagingSenderId: '968202689571',
    projectId: 'echoo-502fb',
    authDomain: 'echoo-502fb.firebaseapp.com',
    storageBucket: 'echoo-502fb.firebasestorage.app',
    measurementId: 'G-WMH0WJRGGE',
  );

}